; syscall name table x64

%define sys.out 1
%define sys.in  0
%define syscall.sys_read 0
%define syscall.sys_write 1
%define syscall.sys_open 2
%define syscall.sys_close 3
%define syscall.sys_stat 4
%define syscall.sys_fstat 5
%define syscall.sys_lstat 6
%define syscall.sys_poll 7
%define syscall.sys_lseek 8
%define syscall.sys_mmap 9
%define syscall.sys_mprotect 10
%define syscall.sys_munmap 11
%define syscall.sys_brk 12
%define syscall.sys_rt_sigaction 13
%define syscall.sys_rt_sigprocmask 14
%define syscall.sys_rt_sigreturn 15
%define syscall.sys_ioctl 16
%define syscall.sys_pread64 17
%define syscall.sys_pwrite64 18
%define syscall.sys_readv 19
%define syscall.sys_writev 20
%define syscall.sys_access 21
%define syscall.sys_pipe 22
%define syscall.sys_select 23
%define syscall.sys_sched_yield 24
%define syscall.sys_mremap 25
%define syscall.sys_msync 26
%define syscall.sys_mincore 27
%define syscall.sys_madvise 28
%define syscall.sys_shmget 29
%define syscall.sys_shmat 30
%define syscall.sys_shmctl 31
%define syscall.sys_dup 32
%define syscall.sys_dup2 33
%define syscall.sys_pause 34
%define syscall.sys_nanosleep 35
%define syscall.sys_getitimer 36
%define syscall.sys_alarm 37
%define syscall.sys_setitimer 38
%define syscall.sys_getpid 39
%define syscall.sys_sendfile 40
%define syscall.sys_socket 41
%define syscall.sys_connect 42
%define syscall.sys_accept 43
%define syscall.sys_sendto 44
%define syscall.sys_recvfrom 45
%define syscall.sys_sendmsg 46
%define syscall.sys_recvmsg 47
%define syscall.sys_shutdown 48
%define syscall.sys_bind 49
%define syscall.sys_listen 50
%define syscall.sys_getsockname 51
%define syscall.sys_getpeername 52
%define syscall.sys_socketpair 53
%define syscall.sys_setsockopt 54
%define syscall.sys_getsockopt 55
%define syscall.sys_clone 56
%define syscall.sys_fork 57
%define syscall.sys_vfork 58
%define syscall.sys_execve 59
%define syscall.sys_exit 60
%define syscall.sys_wait4 61
%define syscall.sys_kill 62
%define syscall.sys_uname 63
%define syscall.sys_semget 64
%define syscall.sys_semop 65
%define syscall.sys_semctl 66
%define syscall.sys_shmdt 67
%define syscall.sys_msgget 68
%define syscall.sys_msgsnd 69
%define syscall.sys_msgrcv 70
%define syscall.sys_msgctl 71
%define syscall.sys_fcntl 72
%define syscall.sys_flock 73
%define syscall.sys_fsync 74
%define syscall.sys_fdatasync 75
%define syscall.sys_truncate 76
%define syscall.sys_ftruncate 77
%define syscall.sys_getdents 78
%define syscall.sys_getcwd 79
%define syscall.sys_chdir 80
%define syscall.sys_fchdir 81
%define syscall.sys_rename 82
%define syscall.sys_mkdir 83
%define syscall.sys_rmdir 84
%define syscall.sys_creat 85
%define syscall.sys_link 86
%define syscall.sys_unlink 87
%define syscall.sys_symlink 88
%define syscall.sys_readlink 89
%define syscall.sys_chmod 90
%define syscall.sys_fchmod 91
%define syscall.sys_chown 92
%define syscall.sys_fchown 93
%define syscall.sys_lchown 94
%define syscall.sys_umask 95
%define syscall.sys_gettimeofday 96
%define syscall.sys_getrlimit 97
%define syscall.sys_getrusage 98
%define syscall.sys_sysinfo 99
%define syscall.sys_times 100
%define syscall.sys_ptrace 101
%define syscall.sys_getuid 102
%define syscall.sys_syslog 103
%define syscall.sys_getgid 104
%define syscall.sys_setuid 105
%define syscall.sys_setgid 106
%define syscall.sys_geteuid 107
%define syscall.sys_getegid 108
%define syscall.sys_setpgid 109
%define syscall.sys_getppid 110
%define syscall.sys_getpgrp 111
%define syscall.sys_setsid 112
%define syscall.sys_setreuid 113
%define syscall.sys_setregid 114
%define syscall.sys_getgroups 115
%define syscall.sys_setgroups 116
%define syscall.sys_setresuid 117
%define syscall.sys_getresuid 118
%define syscall.sys_setresgid 119
%define syscall.sys_getresgid 120
%define syscall.sys_getpgid 121
%define syscall.sys_setfsuid 122
%define syscall.sys_setfsgid 123
%define syscall.sys_getsid 124
%define syscall.sys_capget 125
%define syscall.sys_capset 126
%define syscall.sys_rt_sigpending 127
%define syscall.sys_rt_sigtimedwait 128
%define syscall.sys_rt_sigqueueinfo 129
%define syscall.sys_rt_sigsuspend 130
%define syscall.sys_sigaltstack 131
%define syscall.sys_utime 132
%define syscall.sys_mknod 133
%define syscall.sys_uselib 134
%define syscall.sys_personality 135
%define syscall.sys_ustat 136
%define syscall.sys_statfs 137
%define syscall.sys_fstatfs 138
%define syscall.sys_sysfs 139
%define syscall.sys_getpriority 140
%define syscall.sys_setpriority 141
%define syscall.sys_sched_setparam 142
%define syscall.sys_sched_getparam 143
%define syscall.sys_sched_setscheduler 144
%define syscall.sys_sched_getscheduler 145
%define syscall.sys_sched_get_priority_max 146
%define syscall.sys_sched_get_priority_min 147
%define syscall.sys_sched_rr_get_interval 148
%define syscall.sys_mlock 149
%define syscall.sys_munlock 150
%define syscall.sys_mlockall 151
%define syscall.sys_munlockall 152
%define syscall.sys_vhangup 153
%define syscall.sys_modify_ldt 154
%define syscall.sys_pivot_root 155
%define syscall.sys__sysctl 156
%define syscall.sys_prctl 157
%define syscall.sys_arch_prctl 158
%define syscall.sys_adjtimex 159
%define syscall.sys_setrlimit 160
%define syscall.sys_chroot 161
%define syscall.sys_sync 162
%define syscall.sys_acct 163
%define syscall.sys_settimeofday 164
%define syscall.sys_mount 165
%define syscall.sys_umount2 166
%define syscall.sys_swapon 167
%define syscall.sys_swapoff 168
%define syscall.sys_reboot 169
%define syscall.sys_sethostname 170
%define syscall.sys_setdomainname 171
%define syscall.sys_iopl 172
%define syscall.sys_ioperm 173
%define syscall.sys_create_module 174
%define syscall.sys_init_module 175
%define syscall.sys_delete_module 176
%define syscall.sys_get_kernel_syms 177
%define syscall.sys_query_module 178
%define syscall.sys_quotactl 179
%define syscall.sys_nfsservctl 180
%define syscall.sys_getpmsg 181
%define syscall.sys_putpmsg 182
%define syscall.sys_afs_syscall 183
%define syscall.sys_tuxcall 184
%define syscall.sys_security 185
%define syscall.sys_gettid 186
%define syscall.sys_readahead 187
%define syscall.sys_setxattr 188
%define syscall.sys_lsetxattr 189
%define syscall.sys_fsetxattr 190
%define syscall.sys_getxattr 191
%define syscall.sys_lgetxattr 192
%define syscall.sys_fgetxattr 193
%define syscall.sys_listxattr 194
%define syscall.sys_llistxattr 195
%define syscall.sys_flistxattr 196
%define syscall.sys_removexattr 197
%define syscall.sys_lremovexattr 198
%define syscall.sys_fremovexattr 199
%define syscall.sys_tkill 200
%define syscall.sys_time 201
%define syscall.sys_futex 202
%define syscall.sys_sched_setaffinity 203
%define syscall.sys_sched_getaffinity 204
%define syscall.sys_set_thread_area 205
%define syscall.sys_io_setup 206
%define syscall.sys_io_destroy 207
%define syscall.sys_io_getevents 208
%define syscall.sys_io_submit 209
%define syscall.sys_io_cancel 210
%define syscall.sys_get_thread_area 211
%define syscall.sys_lookup_dcookie 212
%define syscall.sys_epoll_create 213
%define syscall.sys_epoll_ctl_old 214
%define syscall.sys_epoll_wait_old 215
%define syscall.sys_remap_file_pages 216
%define syscall.sys_getdents64 217
%define syscall.sys_set_tid_address 218
%define syscall.sys_restart_syscall 219
%define syscall.sys_semtimedop 220
%define syscall.sys_fadvise64 221
%define syscall.sys_timer_create 222
%define syscall.sys_timer_settime 223
%define syscall.sys_timer_gettime 224
%define syscall.sys_timer_getoverrun 225
%define syscall.sys_timer_delete 226
%define syscall.sys_clock_settime 227
%define syscall.sys_clock_gettime 228
%define syscall.sys_clock_getres 229
%define syscall.sys_clock_nanosleep 230
%define syscall.sys_exit_group 231
%define syscall.sys_epoll_wait 232
%define syscall.sys_epoll_ctl 233
%define syscall.sys_tgkill 234
%define syscall.sys_utimes 235
%define syscall.sys_vserver 236
%define syscall.sys_mbind 237
%define syscall.sys_set_mempolicy 238
%define syscall.sys_get_mempolicy 239
%define syscall.sys_mq_open 240
%define syscall.sys_mq_unlink 241
%define syscall.sys_mq_timedsend 242
%define syscall.sys_mq_timedreceive 243
%define syscall.sys_mq_notify 244
%define syscall.sys_mq_getsetattr 245
%define syscall.sys_kexec_load 246
%define syscall.sys_waitid 247
%define syscall.sys_add_key 248
%define syscall.sys_request_key 249
%define syscall.sys_keyctl 250
%define syscall.sys_ioprio_set 251
%define syscall.sys_ioprio_get 252
%define syscall.sys_inotify_init 253
%define syscall.sys_inotify_add_watch 254
%define syscall.sys_inotify_rm_watch 255
%define syscall.sys_migrate_pages 256
%define syscall.sys_openat 257
%define syscall.sys_mkdirat 258
%define syscall.sys_mknodat 259
%define syscall.sys_fchownat 260
%define syscall.sys_futimesat 261
%define syscall.sys_newfstatat 262
%define syscall.sys_unlinkat 263
%define syscall.sys_renameat 264
%define syscall.sys_linkat 265
%define syscall.sys_symlinkat 266
%define syscall.sys_readlinkat 267
%define syscall.sys_fchmodat 268
%define syscall.sys_faccessat 269
%define syscall.sys_pselect6 270
%define syscall.sys_ppoll 271
%define syscall.sys_unshare 272
%define syscall.sys_set_robust_list 273
%define syscall.sys_get_robust_list 274
%define syscall.sys_splice 275
%define syscall.sys_tee 276
%define syscall.sys_sync_file_range 277
%define syscall.sys_vmsplice 278
%define syscall.sys_move_pages 279
%define syscall.sys_utimensat 280
%define syscall.sys_epoll_pwait 281
%define syscall.sys_signalfd 282
%define syscall.sys_timerfd_create 283
%define syscall.sys_eventfd 284
%define syscall.sys_fallocate 285
%define syscall.sys_timerfd_settime 286
%define syscall.sys_timerfd_gettime 287
%define syscall.sys_accept4 288
%define syscall.sys_signalfd4 289
%define syscall.sys_eventfd2 290
%define syscall.sys_epoll_create1 291
%define syscall.sys_dup3 292
%define syscall.sys_pipe2 293
%define syscall.sys_inotify_init1 294
%define syscall.sys_preadv 295
%define syscall.sys_pwritev 296
%define syscall.sys_rt_tgsigqueueinfo 297
%define syscall.sys_perf_event_open 298
%define syscall.sys_recvmmsg 299
%define syscall.sys_fanotify_init 300
%define syscall.sys_fanotify_mark 301
%define syscall.sys_prlimit64 302
%define syscall.sys_name_to_handle_at 303
%define syscall.sys_open_by_handle_at 304
%define syscall.sys_clock_adjtime 305
%define syscall.sys_syncfs 306
%define syscall.sys_sendmmsg 307
%define syscall.sys_setns 308
%define syscall.sys_getcpu 309
%define syscall.sys_process_vm_readv 310
%define syscall.sys_process_vm_writev 311
%define syscall.sys_kcmp 312
%define syscall.sys_finit_module 313
%define syscall.sys_sched_setattr 314
%define syscall.sys_sched_getattr 315
%define syscall.sys_renameat2 316
%define syscall.sys_seccomp 317
%define syscall.sys_getrandom 318
%define syscall.sys_memfd_create 319
%define syscall.sys_kexec_file_load 320
%define syscall.sys_bpf 321
%define syscall.stub_execveat 322
%define syscall.userfaultfd 323
%define syscall.membarrier 324
%define syscall.mlock2 325
%define syscall.copy_file_range 326
%define syscall.preadv2 327
%define syscall.pwritev2 328
%define syscall.pkey_mprotect1 329
%define syscall.pkey_alloc 330
%define syscall.pkey_free 331
%define syscall.statx 332
%define syscall.io_pgetevents 333
%define syscall.rseq 334
%define syscall.pkey_mprotect2 335
;;head
;;required